# Generated by Django 2.1.2 on 2018-10-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20181020_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Property')),
            ],
        ),
        migrations.AddField(
            model_name='fechareserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva'),
        ),
    ]
