# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20181106_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
